apiVersion: template.openshift.io/v1
kind: Template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true

objects:
- apiVersion: authorization.openshift.io/v1
  kind: Role
  metadata:
    annotations:
      openshift.io/description: A user who can deploy applications
      openshift.io/reconcile-protect: "false"
    name: ${PREFIX}deployer
  rules:
  - apiGroups:
    - image.openshift.io
    resources:
    - imagestreamimages
    - imagestreammappings
    - imagestreams
    - imagestreamtags
    verbs:
    - get
    - list
    - watch
    - update
  - apiGroups:
    - project.openshift.io
    - ""
    attributeRestrictions: null
    resources:
    - projects
    verbs:
    - get
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - persistentvolumeclaims
    - services
    - configmaps
    - pods
    verbs:
    - list
    - get
    - create
    - update
    - patch
  - apiGroups:
    - apps.openshift.io
    attributeRestrictions: null
    resources:
    - deploymentconfigs
    verbs:
    - get
    - create
    - update
    - patch
  - apiGroups:
    - route.openshift.io
    attributeRestrictions: null
    resources:
    - routes
    verbs:
    - get
    - create
    - update
    - patch
  - apiGroups:
    - template.openshift.io
    attributeRestrictions: null
    resources:
    - processedtemplates
    verbs:
    - create
  - apiGroups:
    - route.openshift.io
    attributeRestrictions: null
    resources:
    - routes
    verbs:
    - get
    - create
    - update
    - patch
  - apiGroups:
    - route.openshift.io
    - ""
    attributeRestrictions: null
    resources:
    - routes/custom-host
    verbs:
    - create
  - apiGroups:
    - batch
    attributeRestrictions: null
    resources:
    - jobs
    verbs:
    - create
    - delete
    - get
