apiVersion: template.openshift.io/v1
kind: Template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true

objects:
- apiVersion: authorization.openshift.io/v1
  kind: Role
  metadata:
    annotations:
      openshift.io/description: A user who can trigger new builds but cannot delete them.
      openshift.io/reconcile-protect: "false"
    name: ${PREFIX}deployer
  rules:
  - apiGroups:
    - image.openshift.io
    resources:
    - imagestreamimages
    - imagestreammappings
    - imagestreams
    - imagestreamtags
    verbs:
    - get
    - list
    - watch
    - update
  - apiGroups:
    - project.openshift.io
    - ""
    attributeRestrictions: null
    resources:
    - projects
    verbs:
    - get
