apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "pg-version-upgrade.labels" . | indent 4 }}
spec:
  postgresClusterName: {{ .Values.pgUpgrade.postgresClusterName }}
  fromPostgresVersion: {{ .Values.pgUpgrade.fromPostgresVersion }}
  toPostgresVersion: {{ .Values.pgUpgrade.toPostgresVersion }}
