apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  labels:
{{ include "pg-version-upgrade.labels" . | indent 4 }}
  annotations:
    openshift.io/description: A user who can annotate and shutdown postgres clusters
    openshift.io/reconcile-protect: "false"
  name: {{ .Release.Name }}-pg-version-upgrade
rules:
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - postgresclusters
    verbs:
      - get
      - patch
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - pgupgrades
    verbs:
      - get
      