kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-pg-version-upgrade
  labels:
{{ include "pg-version-upgrade.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-pg-version-upgrade
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-pg-version-upgrade
    namespace: {{ .Release.Namespace }}