kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pg-version-upgrade
  labels:
{{ include "pg-version-upgrade.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: dockerhub-registry
