apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "pg-version-upgrade.fullname" . }}-wait-for-completion
  labels:
{{ include "pg-version-upgrade.labels" . | indent 4 }}
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 3
  template:
    metadata:
      name: {{ template "pg-version-upgrade.fullname" . }}-wait-for-completion
      labels: {{ include "pg-version-upgrade.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-pg-version-upgrade
      containers:
        - name: {{ template "pg-version-upgrade.fullname" . }}-wait-for-completion
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          image: bitnami/kubectl:{{ .Values.kubernetesVersion }}
          command:
            - "bin/bash"
            - "-c"
            - |
              set -euxo pipefail;
              
              exit 0;
      restartPolicy: Never