kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-allow-crunchydb-ha
  labels: {{ include "cas-postgres-cluster.labels" . | nindent 4 }}
    postgres-operator.crunchydata.com/cluster: {{ .Release.Name }}-cas-postgres-cluster
spec:
  podSelector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: {{ .Release.Name }}-cas-postgres-cluster
  ingress:
    - from:
        - podSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: {{ .Release.Name }}-cas-postgres-cluster

