apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true

objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${PREFIX}ciip-postgres-master
      labels:
        name: ${PREFIX}ciip-postgres-master
    spec:
      selector:
        name: ${PREFIX}ciip-postgres-master
      clusterIP: None
      ports:
      - port: 5432
