version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.1.0

jobs:
  create-local-cluster:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - checkout
      - redhat-openshift/create-local-cluster-with-oc:
          skip-registry-check: true
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          password: password
          server-address: 'https://127.0.0.1:8443'
          username: dev1
      - run:
          command: >
            oc new-project wksv3k-tools

            oc new-project wksv3k-test

            oc new-project wksv3k-dev

            oc new-project wksv3k-prod
          name: Create the cluster project set
  build:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - run:
          command: make configure
          name: Configure the cluster
      - run:
          command: make build
          name: Build image on the cluster
  deploy-test:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - run:
          command: make deploy_test
          name: Deploy to test
  deploy-dev:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - run:
          command: make deploy_test
          name: Deploy to dev
  deploy-prod:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - run:
          command: make deploy_test
          name: Deploy to prod

workflows:
  deployment:
    jobs:
      - create-local-cluster
      - build
      - deploy-test
      - deploy-dev
      - deploy-prod
