version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0
  orb-tools: circleci/orb-tools@8.27.4

executors:
  ruby:
    docker:
      - image: "circleci/ruby:2.6.4"

jobs:
  lint:
    executor: redhat-openshift/default
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          server-address: $OC_SERVER_ADDRESS
          token: $OC_TOKEN
      - run:
          command: make lint
          name: Lint the openshift yaml

  test-unit:
    executor: ruby
    steps:
      - orb-tools/install-bats
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule update --init
      - run:
          command: make test_unit
          name: Run unit tests via make

workflows:
  test:
    jobs:
      - test-unit:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: gh-pages
