version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.1.0

jobs:
  create-local-cluster:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - redhat-openshift/create-local-cluster-with-oc:
          skip-registry-check: true
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          password: password
          server-address: 'https://127.0.0.1:8443'
          username: dev1
      - run:
          command: >
            oc new-project localclustertestproject

            oc new-app
            centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git

            kubectl get services
          name: Test the cluster
  build:
    - make build
