version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0
  orb-tools: circleci/orb-tools@8.27.4
  gcp-gcr: circleci/gcp-gcr@0.7.1

executors:
  ruby:
    docker:
      - image: "circleci/ruby:2.6.4"

jobs:
  test-local-cluster:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Add Docker registry to /etc/hosts
          command: echo "172.30.1.1 docker-registry.default.svc" | sudo tee -a /etc/hosts
      - redhat-openshift/create-local-cluster-with-oc:
          skip-registry-check: true
      - run:
          command: docker login -u "$RED_HAT_DOCKER_USERNAME" -p "$RED_HAT_DOCKER_PASSWORD" "$RED_HAT_DOCKER_SERVER"
          name: Log in to Red Hat docker registry
      - run:
          name: Login as cluster admin
          command: oc login -u system:admin
      - run:
          command: make mock_storageclass
          name: Mock the storage classes
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          password: password
          server-address: "https://127.0.0.1:8443"
          username: dev1
      - run:
          command: make provision
          name: Provision the cluster project set
      - run:
          command: make configure
          name: Configure the cluster
      - run:
          command: make build
          name: Build image on the cluster
      - run:
          command: make test_e2e_setup
          name: Setup for e2e test
      - run:
          command: >
            make install_dev
            MASTER_CPU_REQUEST="300m" MASTER_CPU_LIMIT="300m"
            WORKER_CPU_REQUEST="300m" WORKER_CPU_LIMIT="300m"
            MASTER_MEMORY_REQUEST="512Mi" MASTER_MEMORY_LIMIT="512Mi"
            WORKER_MEMORY_REQUEST="512Mi" WORKER_MEMORY_LIMIT="512Mi"
            POSTGRESQL_WORKERS=2
          name: Deploy to dev
      - run:
          command: make test_e2e OC_PROJECT=wksv3k-dev
          name: Run e2e tests on dev

  lint:
    executor: redhat-openshift/default
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          server-address: $OC_SERVER_ADDRESS
          token: $OC_TOKEN
      - run:
          command: make lint
          name: Lint the openshift yaml

  build_and_push:
    executor: gcp-gcr/default
    parameters:
      image_tag:
        type: string
      cache_version:
        type: integer
        default: 2
    steps:
      - checkout
      - run:
          command: docker login -u "$RED_HAT_DOCKER_USERNAME" -p "$RED_HAT_DOCKER_PASSWORD" "$RED_HAT_DOCKER_SERVER"
          name: Log in to Red Hat docker registry
      - gcp-gcr/gcr-auth
      - restore_cache:
          keys:
            - v<< parameters.cache_version>>-cas-postgres-{{ .Branch }}
          paths:
            - /tmp/cas-postgres.tar
      - run:
          name: Load cache
          command: |
            set +o pipefail
            docker load -i /tmp/cas-postgres.tar | true
      - gcp-gcr/build-image:
          image: cas-postgres
          tag: << parameters.image_tag >>
      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o /tmp/cas-postgres.tar gcr.io/${GOOGLE_PROJECT_ID}/cas-postgres
      - save_cache:
          key: v<< parameters.cache_version>>-cas-postgres-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/cas-postgres.tar
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: cas-postgres
          tag: << parameters.image_tag >>
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  test-unit:
    executor: ruby
    steps:
      - orb-tools/install-bats
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          command: make test_unit
          name: Run unit tests via make

workflows:
  test:
    jobs:
      # - lint:
      #     context: cas-pipeline
      - test-unit
      - build_and_push:
          image_tag: ${CIRCLE_SHA1}
          context: cas-pipeline
          requires:
            - test-unit
      # - test-local-cluster:
      #     context: cas-pipeline
      #     requires:
      #       - lint
      #       - test-unit
