version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0

jobs:
  test-local-cluster:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - checkout
      - redhat-openshift/create-local-cluster-with-oc:
          skip-registry-check: true
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          password: password
          server-address: 'https://127.0.0.1:8443'
          username: dev1
      - run:
          command: docker login -u "$RED_HAT_DOCKER_USERNAME" -p "$RED_HAT_DOCKER_PASSWORD" "$RED_HAT_DOCKER_SERVER"
          name: Log in to Red Hat docker registry
      - run:
          command: make provision
          name: Provision the cluster project set
      - run:
          command: make configure
          name: Configure the cluster
      - run:
          command: make build
          name: Build image on the cluster
      - run:
          command: make deploy_test
          name: Deploy to test
      - run:
          command: make deploy_test
          name: Deploy to dev
      - run:
          command: make deploy_test
          name: Deploy to prod

  lint:
    executor: redhat-openshift/default
    steps:
      - checkout
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          server-address: $OC_SERVER_ADDRESS
          token: $OC_TOKEN
      - run:
          command: make lint
          name: Lint the openshift yaml

workflows:
  test:
    jobs:
      - lint
      - test-local-cluster:
          requires:
            - lint
