version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.1.0

jobs:
  create-local-cluster:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - checkout
      - redhat-openshift/create-local-cluster-with-oc:
          skip-registry-check: true
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          password: password
          server-address: 'https://127.0.0.1:8443'
          username: dev1
      - run:
          command: oc new-project localclustertestproject
          name: Create a test project on the cluster
      - run:
          command: make configure
          name: Configure the cluster
      - run:
          command: make build
          name: Build image on the cluster

workflows:
  deployment:
    jobs:
      - create-local-cluster
