apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: cas-postgres
  name: cas-postgres
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: 'cas-postgres:latest'
  postCommit:
    script: 'psql -c "select true"'
  resources:
    limits:
      cpu: '1'
      memory: 512Mi
    requests:
      cpu: 750m
      memory: 256Mi
  runPolicy: Parallel
  source:
    git:
      ref: develop
      uri: 'https://github.com/bcgov/cas-postgres.git'
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
  successfulBuildsHistoryLimit: 5
