apiVersion: template.openshift.io/v1
kind: Template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${PREFIX}ciip-postgres-master
  spec:
    storageClassName: netapp-block-standard
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
