apiVersion: v1
kind: Secret
metadata:
  name: {{ template "patroni-migration.fullname" . }}-migrated-secret
  labels:
{{ include "patroni-migration.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    # Secret is added last
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  migrated: {{ "migrated!" | b64enc }}

