kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-database-migration
  labels:
{{ include "patroni-migration.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-200"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed,before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-database-migration
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-database-migration
    namespace: {{ .Release.Namespace }}