apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "patroni.fullname" . }}-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ template "patroni.fullname" . }}
      release: {{ .Release.Name }}
