# dev, test, prod
environment: ~

postgresCluster:
  postgresVersion: 17
  storageSize: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  wal:
    storageSize: 1Gi

  postgres:
    replicaCount: 2
  pgbackrest:
    # Resources for the pgbackrest sidecar container
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  pgbouncer:
    replicaCount: 2
  # Resources for the "obps-postgres-repo-host" pod
  repoHost:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  # The "users" value(s) is passed to the crunchy postgres operator to create the database.
  # See https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management
  users:
    - name: postgres
      databases:
        - test

gcsBackups:
  enable: false
  # Needs to match the "namespace_apps" value in the terraform provisioning chart.
  # example syntax: bucketName
  bucketName: ~

terraform-bucket-provision:
  terraform:
    # example syntax: '["bucketName"]'
    namespace_apps: ~
    # !important: unique for the deployment
    workspace: ~

# To configure a KNP allowing external access, for metabase for example
external-access:
  enabled: false
  instanceName: cas-metabase
  prefix: ~
  environment: ~
