# dev, test, prod
environment: ~

postgresCluster:
  postgresVersion: 15
  storageSize: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  postgres:
    image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres
    tag: ubi8-15.7-0
    replicaCount: 2
  # pgbackrest:
  #   image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbackrest
  #   tag: ubi8-2.41-4
  pgbouncer:
    # image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbouncer
    # tag: ubi8-1.18-0
    replicaCount: 2

  # The "users" value(s) is passed to the crunchy postgres operator to create the database.
  # See https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management
  users:
    - name: postgres
      databases:
        - test

gcsBackups:
  enable: false
  # Needs to match the "namespace_apps" value in the terraform provisioning chart.
  # example syntax: bucketName
  bucketName: ~

terraform-bucket-provision:
  terraform:
    # example syntax: '["bucketName"]'
    namespace_apps: ~
    # !important: unique for the deployment
    workspace: ~

# To configure a KNP allowing external access, for metabase for example
external-access:
  enabled: false
  instanceName: cas-metabase
  prefix: ~
  environment: ~
