apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: Openshift project name
    displayName: Project
    name: OC_PROJECT
    required: true

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${PREFIX}ciip-postgres-shelf-tfe-add-app
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: ${PREFIX}ciip-postgres-shelf-tfe-add-app
        spec:
          containers:
            - name: cas-shelf-tfe-add-app
              resources:
                limits:
                  cpu: '1'
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 512Mi
              image: docker.pkg.github.com/bcgov/cas-shelf/cas-shelf-tfe-add-app:0.1
              env:
                - name: TFC_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: terraform-cloud-workspace
                - name: TFC_WORKSPACE_ID
                  valueFrom:
                    secretKeyRef:
                      key: workspace_id
                      name: terraform-cloud-workspace
              command: ["bash",  "/script.sh", "${OC_PROJECT}"", "${PREFIX}ciip-postgres-walg"]
          restartPolicy: Never
