apiVersion: v1
name: patroni
description: "Highly available elephant herd: HA PostgreSQL cluster."
version: 0.21.4
appVersion: 1.6-p3
home: https://github.com/zalando/patroni
sources:
  - https://github.com/zalando/patroni
  - https://github.com/zalando/spilo
maintainers:
  - name: Dylan Leard
    email: dylan@button.is
  - name: Pierre Bastianelli
    email: pierre.bastianelli@gov.bc.ca
