{{- if .Values.patroni.walE.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-postgres.fullname" . }}-cas-shelf-walg-bucket-provider
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: {{ template "cas-postgres.fullname" . }}-cas-shelf-walg-bucket-provider
      labels: {{ include "cas-postgres.labels" . | nindent 12 }}
    spec:
      containers:
        - name: {{ template "cas-postgres.fullname" . }}-cas-shelf-walg-bucket-provider
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          image: gcr.io/ggl-cas-storage/cas-shelf-tfe-add-app:0.1
          imagePullPolicy: Always
          env:
            - name: TFC_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: terraform-cloud-workspace
            - name: TFC_WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  key: workspace_id
                  name: terraform-cloud-workspace
          command: ["bash",  "/script.sh", {{ .Values.namespace | quote }}, {{ .Values.gcs.bucketSuffix | quote }}]
      restartPolicy: Never
{{- end }}
