{{- if .Values.citus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cas-postgres.fullname" . }}-workers
  labels:
    app: {{ template "cas-postgres.name" . }}
    component: worker
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.service.port }}
    targetPort: postgresql
  {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
  {{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "cas-postgres.name" . }}
    component: worker
    release: {{ .Release.Name }}
{{- end }}
