apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cas-postgres
spec:
  replicas: 1
  selector:
    name: cas-postgres
  template:
    metadata:
      matchLabels:
        name: cas-postgres
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: cas-postgres
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: cas-postgres
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: cas-postgres
        - name: POSTGRESQL_MAX_CONNECTIONS
          value: '1000'
        - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
          value: '1000'
        - name: POSTGRESQL_SHARED_BUFFERS
          value: 2GB
        - name: POSTGRESQL_EFFECTIVE_CACHE_SIZE
          value: 8GB
        image: cas-postgres
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: cas-postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 16Gi
            cpu: 8000m
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: cas-postgres
      volumes:
      - name: cas-postgres
        persistentVolumeClaim:
          claimName: cas-postgres
