apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: SHA1 of git revision to be deployed.
    displayName: Git SHA1
    name: GIT_SHA1
    required: true
  - description: Base64-encoded password for the postgres user.
    displayName: Postgres Password
    name: POSTGRESQL_ADMIN_PASSWORD
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        beta.kubernetes.io/os: linux
      name: ${PREFIX}ciip-postgres-master
    type: Opaque
    data:
      postgresqlAdminPassword: ${POSTGRESQL_ADMIN_PASSWORD}
