image:
  repository:  gcr.io/ggl-cas-storage/cas-postgres
  pullPolicy: Always
  tag: 4392eebef40e95b3faa5b3d35483b59b1719fc2a

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

persistence:
  storageClass: gluster-block
  size: 1Gi

namespace: wksv3k-dev
walgArchive:
  enabled: false

## Use Existing secret instead of creating one
## It must have a postgres-password key containing the desired password
# existingSecret: 'secret'

service:
  type: ClusterIP
  port: 5432
  externalIPs: []

citus:
  enabled: true
  replicas: 2
