apiVersion: v2
name: cas-postgres
description: Postgres database for the CAS team
type: application
version: 0.4.0
appVersion: 0.1.0
dependencies:
- name: patroni
  version: "0.20.0"
  repository: "file://../patroni"
