image:
  repository:  gcr.io/ggl-cas-storage/cas-postgres
  pullPolicy: Always
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
persistence:
  storageClass: netapp-block-standard
  size: 20Gi

namespace: ""
walgArchive:
  enabled: false
  # the GCS bucket name will be {{ namespace }}-{{ walgArchive.bucketSuffix }}
  bucketSuffix: "pg-walg"


## Use Existing secret instead of creating one
## It must have a postgres-password key containing the desired password
# existingSecret: 'secret'

service:
  port: 5432

citus:
  enabled: false
  replicas: 4
