image:
  repository:  gcr.io/ggl-cas-storage/cas-postgres
  pullPolicy: Always
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
persistence:
  storageClass: netapp-block-standard
  size: 20Gi

namespace: ""
walgArchive:
  enabled: false
