patroni:
  image:
    repository: gcr.io/ggl-cas-storage/cas-postgres
    pullPolicy: Always
    tag: "0.1.2"

  replicaCount: 2

  resources: {}
  credentials:
    random: true
  persistentVolume:
    storageClass: gluster-block
    size: 1Gi
  # As per https://patroni.readthedocs.io/en/latest/kubernetes.html#use-configmaps
  # "in some cases, for instance, when running on OpenShift, there is no alternative to using ConfigMaps."
  kubernetes:
    dcs:
      enable: true
    configmaps:
      enable: true
  walE:
    enable:
      false
      # the GCS bucket name should be {{ namespace }}-{{ gcs.bucketSuffix }}
    gcsBucket:
    # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
    kubernetesSecret:

# options below are required if walE.enable is true
namespace:
gcs:
  bucketSuffix:
