name: Build and Test

on:
  push:
    branches: [develop]
  pull_request: 
    branches: [develop]


jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Bats
        uses: bats-core/bats-action@2.0.0
      - run: make test_unit
